# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"\x07\n\x05\x45mpty\"0\n\x0b\x43hatRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\"d\n\x0c\x43hatResponse\x12\x0f\n\x05token\x18\x01 \x01(\tH\x00\x12\x17\n\rerror_message\x18\x02 \x01(\tH\x00\x12\x19\n\x0fsource_document\x18\x03 \x01(\tH\x00\x42\x0f\n\rresponse_type\"\x1b\n\tEmbedding\x12\x0e\n\x06values\x18\x01 \x03(\x02\"&\n\x15\x45mbeddingBatchRequest\x12\r\n\x05texts\x18\x01 \x03(\t\"B\n\x16\x45mbeddingBatchResponse\x12(\n\nembeddings\x18\x01 \x03(\x0b\x32\x14.inference.Embedding\"\x9b\x01\n\x11ModelListResponse\x12\x19\n\x11generation_models\x18\x01 \x03(\t\x12\x18\n\x10\x65mbedding_models\x18\x02 \x03(\t\x12 \n\x18\x63urrent_generation_model\x18\x03 \x01(\t\x12\x1f\n\x17\x63urrent_embedding_model\x18\x04 \x01(\t\x12\x0e\n\x06\x64\x65vice\x18\x05 \x01(\t\"R\n\x12SwitchModelRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12(\n\nmodel_type\x18\x02 \x01(\x0e\x32\x14.inference.ModelType\"7\n\x13SwitchModelResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t*7\n\tModelType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0e\n\nGENERATION\x10\x01\x12\r\n\tEMBEDDING\x10\x02\x32\xc3\x02\n\x10InferenceService\x12?\n\nChatStream\x12\x16.inference.ChatRequest\x1a\x17.inference.ChatResponse0\x01\x12\x45\n\x13ListAvailableModels\x12\x10.inference.Empty\x1a\x1c.inference.ModelListResponse\x12L\n\x0bSwitchModel\x12\x1d.inference.SwitchModelRequest\x1a\x1e.inference.SwitchModelResponse\x12Y\n\x12GetEmbeddingsBatch\x12 .inference.EmbeddingBatchRequest\x1a!.inference.EmbeddingBatchResponseb\x06proto3')

_MODELTYPE = DESCRIPTOR.enum_types_by_name['ModelType']
ModelType = enum_type_wrapper.EnumTypeWrapper(_MODELTYPE)
UNKNOWN = 0
GENERATION = 1
EMBEDDING = 2


_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_CHATREQUEST = DESCRIPTOR.message_types_by_name['ChatRequest']
_CHATRESPONSE = DESCRIPTOR.message_types_by_name['ChatResponse']
_EMBEDDING = DESCRIPTOR.message_types_by_name['Embedding']
_EMBEDDINGBATCHREQUEST = DESCRIPTOR.message_types_by_name['EmbeddingBatchRequest']
_EMBEDDINGBATCHRESPONSE = DESCRIPTOR.message_types_by_name['EmbeddingBatchResponse']
_MODELLISTRESPONSE = DESCRIPTOR.message_types_by_name['ModelListResponse']
_SWITCHMODELREQUEST = DESCRIPTOR.message_types_by_name['SwitchModelRequest']
_SWITCHMODELRESPONSE = DESCRIPTOR.message_types_by_name['SwitchModelResponse']
Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'inference_pb2'
  # @@protoc_insertion_point(class_scope:inference.Empty)
  })
_sym_db.RegisterMessage(Empty)

ChatRequest = _reflection.GeneratedProtocolMessageType('ChatRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHATREQUEST,
  '__module__' : 'inference_pb2'
  # @@protoc_insertion_point(class_scope:inference.ChatRequest)
  })
_sym_db.RegisterMessage(ChatRequest)

ChatResponse = _reflection.GeneratedProtocolMessageType('ChatResponse', (_message.Message,), {
  'DESCRIPTOR' : _CHATRESPONSE,
  '__module__' : 'inference_pb2'
  # @@protoc_insertion_point(class_scope:inference.ChatResponse)
  })
_sym_db.RegisterMessage(ChatResponse)

Embedding = _reflection.GeneratedProtocolMessageType('Embedding', (_message.Message,), {
  'DESCRIPTOR' : _EMBEDDING,
  '__module__' : 'inference_pb2'
  # @@protoc_insertion_point(class_scope:inference.Embedding)
  })
_sym_db.RegisterMessage(Embedding)

EmbeddingBatchRequest = _reflection.GeneratedProtocolMessageType('EmbeddingBatchRequest', (_message.Message,), {
  'DESCRIPTOR' : _EMBEDDINGBATCHREQUEST,
  '__module__' : 'inference_pb2'
  # @@protoc_insertion_point(class_scope:inference.EmbeddingBatchRequest)
  })
_sym_db.RegisterMessage(EmbeddingBatchRequest)

EmbeddingBatchResponse = _reflection.GeneratedProtocolMessageType('EmbeddingBatchResponse', (_message.Message,), {
  'DESCRIPTOR' : _EMBEDDINGBATCHRESPONSE,
  '__module__' : 'inference_pb2'
  # @@protoc_insertion_point(class_scope:inference.EmbeddingBatchResponse)
  })
_sym_db.RegisterMessage(EmbeddingBatchResponse)

ModelListResponse = _reflection.GeneratedProtocolMessageType('ModelListResponse', (_message.Message,), {
  'DESCRIPTOR' : _MODELLISTRESPONSE,
  '__module__' : 'inference_pb2'
  # @@protoc_insertion_point(class_scope:inference.ModelListResponse)
  })
_sym_db.RegisterMessage(ModelListResponse)

SwitchModelRequest = _reflection.GeneratedProtocolMessageType('SwitchModelRequest', (_message.Message,), {
  'DESCRIPTOR' : _SWITCHMODELREQUEST,
  '__module__' : 'inference_pb2'
  # @@protoc_insertion_point(class_scope:inference.SwitchModelRequest)
  })
_sym_db.RegisterMessage(SwitchModelRequest)

SwitchModelResponse = _reflection.GeneratedProtocolMessageType('SwitchModelResponse', (_message.Message,), {
  'DESCRIPTOR' : _SWITCHMODELRESPONSE,
  '__module__' : 'inference_pb2'
  # @@protoc_insertion_point(class_scope:inference.SwitchModelResponse)
  })
_sym_db.RegisterMessage(SwitchModelResponse)

_INFERENCESERVICE = DESCRIPTOR.services_by_name['InferenceService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MODELTYPE._serialized_start=627
  _MODELTYPE._serialized_end=682
  _EMPTY._serialized_start=30
  _EMPTY._serialized_end=37
  _CHATREQUEST._serialized_start=39
  _CHATREQUEST._serialized_end=87
  _CHATRESPONSE._serialized_start=89
  _CHATRESPONSE._serialized_end=189
  _EMBEDDING._serialized_start=191
  _EMBEDDING._serialized_end=218
  _EMBEDDINGBATCHREQUEST._serialized_start=220
  _EMBEDDINGBATCHREQUEST._serialized_end=258
  _EMBEDDINGBATCHRESPONSE._serialized_start=260
  _EMBEDDINGBATCHRESPONSE._serialized_end=326
  _MODELLISTRESPONSE._serialized_start=329
  _MODELLISTRESPONSE._serialized_end=484
  _SWITCHMODELREQUEST._serialized_start=486
  _SWITCHMODELREQUEST._serialized_end=568
  _SWITCHMODELRESPONSE._serialized_start=570
  _SWITCHMODELRESPONSE._serialized_end=625
  _INFERENCESERVICE._serialized_start=685
  _INFERENCESERVICE._serialized_end=1008
# @@protoc_insertion_point(module_scope)
