# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"\x07\n\x05\x45mpty\"0\n\x0b\x43hatRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\"d\n\x0c\x43hatResponse\x12\x0f\n\x05token\x18\x01 \x01(\tH\x00\x12\x17\n\rerror_message\x18\x02 \x01(\tH\x00\x12\x19\n\x0fsource_document\x18\x03 \x01(\tH\x00\x42\x0f\n\rresponse_type\"\x8b\x01\n\x11ModelListResponse\x12\x19\n\x11generation_models\x18\x01 \x03(\t\x12\x18\n\x10\x65mbedding_models\x18\x02 \x03(\t\x12 \n\x18\x63urrent_generation_model\x18\x03 \x01(\t\x12\x1f\n\x17\x63urrent_embedding_model\x18\x04 \x01(\t\"R\n\x12SwitchModelRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12(\n\nmodel_type\x18\x02 \x01(\x0e\x32\x14.inference.ModelType\"7\n\x13SwitchModelResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t*7\n\tModelType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0e\n\nGENERATION\x10\x01\x12\r\n\tEMBEDDING\x10\x02\x32\xe8\x01\n\x10InferenceService\x12?\n\nChatStream\x12\x16.inference.ChatRequest\x1a\x17.inference.ChatResponse0\x01\x12\x45\n\x13ListAvailableModels\x12\x10.inference.Empty\x1a\x1c.inference.ModelListResponse\x12L\n\x0bSwitchModel\x12\x1d.inference.SwitchModelRequest\x1a\x1e.inference.SwitchModelResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODELTYPE']._serialized_start=474
  _globals['_MODELTYPE']._serialized_end=529
  _globals['_EMPTY']._serialized_start=30
  _globals['_EMPTY']._serialized_end=37
  _globals['_CHATREQUEST']._serialized_start=39
  _globals['_CHATREQUEST']._serialized_end=87
  _globals['_CHATRESPONSE']._serialized_start=89
  _globals['_CHATRESPONSE']._serialized_end=189
  _globals['_MODELLISTRESPONSE']._serialized_start=192
  _globals['_MODELLISTRESPONSE']._serialized_end=331
  _globals['_SWITCHMODELREQUEST']._serialized_start=333
  _globals['_SWITCHMODELREQUEST']._serialized_end=415
  _globals['_SWITCHMODELRESPONSE']._serialized_start=417
  _globals['_SWITCHMODELRESPONSE']._serialized_end=472
  _globals['_INFERENCESERVICE']._serialized_start=532
  _globals['_INFERENCESERVICE']._serialized_end=764
# @@protoc_insertion_point(module_scope)
