# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import inference_pb2 as inference__pb2


class InferenceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ChatStream = channel.unary_stream(
                '/inference.InferenceService/ChatStream',
                request_serializer=inference__pb2.ChatRequest.SerializeToString,
                response_deserializer=inference__pb2.ChatResponse.FromString,
                )
        self.ListAvailableModels = channel.unary_unary(
                '/inference.InferenceService/ListAvailableModels',
                request_serializer=inference__pb2.Empty.SerializeToString,
                response_deserializer=inference__pb2.ModelListResponse.FromString,
                )
        self.SwitchModel = channel.unary_unary(
                '/inference.InferenceService/SwitchModel',
                request_serializer=inference__pb2.SwitchModelRequest.SerializeToString,
                response_deserializer=inference__pb2.SwitchModelResponse.FromString,
                )


class InferenceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ChatStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAvailableModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SwitchModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ChatStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ChatStream,
                    request_deserializer=inference__pb2.ChatRequest.FromString,
                    response_serializer=inference__pb2.ChatResponse.SerializeToString,
            ),
            'ListAvailableModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAvailableModels,
                    request_deserializer=inference__pb2.Empty.FromString,
                    response_serializer=inference__pb2.ModelListResponse.SerializeToString,
            ),
            'SwitchModel': grpc.unary_unary_rpc_method_handler(
                    servicer.SwitchModel,
                    request_deserializer=inference__pb2.SwitchModelRequest.FromString,
                    response_serializer=inference__pb2.SwitchModelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inference.InferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InferenceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ChatStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/inference.InferenceService/ChatStream',
            inference__pb2.ChatRequest.SerializeToString,
            inference__pb2.ChatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListAvailableModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/inference.InferenceService/ListAvailableModels',
            inference__pb2.Empty.SerializeToString,
            inference__pb2.ModelListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SwitchModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/inference.InferenceService/SwitchModel',
            inference__pb2.SwitchModelRequest.SerializeToString,
            inference__pb2.SwitchModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
